name: MirrorDamage
main: de.elia.cameraplugin.mirrordamage.MirrorDamagePlugin
version: 1.2.0 # Version erhöhen ist gute Praxis
api-version: 1.21
author: YourName

commands:
  damgesarmor:
    description: Spawn/entfernt deinen Test-ArmorStand
    usage: /<command>
  mirrordamage: # NEUER BEFEHL
    description: Schaltet den Schadenstransfer für deinen Test-ArmorStand an/aus.
    usage: /<command>
    aliases: [md] # optionaler Alias

permissions:
  mirrordamage.toggle:
    description: Erlaubt das Nutzen von /damgesarmor und /mirrordamage
    default: true