name: MirrorDamage
main: de.elia.cameraplugin.mirrordamage.MirrorDamagePlugin
version: 1.2.0
api-version: 1.21
author: YourName

commands:
  mirrordamage:
    aliases: md
    description: Spawn/entfernt deinen Test‑Villager
    usage: /<command>

permissions:
  mirrordamage.toggle:
    description: Erlaubt das Nutzen von /mirrordamage
    default: true
